### ISSUE TITLE
White logo on white background

### ISSUE THREAD

**Issue by jackallnutt** [cnorthwood/gocd-tls-auth#2]
GoCD's login dialog now has a white background, meaning that the icon button used to log in with a certificate is not visible.

<img width="485" alt="Screen Shot 2019-10-16 at 11 03 51" src="https://user-images.githubusercontent.com/10049968/66909508-ca88a900-f004-11e9-97bf-6f271cb591b2.png">

**Comment by cnorthwood** [comment]
Want me to fix this, or do you fancy sending me a PR?

**Comment by jackallnutt** [comment]
Looks like you fixed it already! 😅

**Comment by cnorthwood** [comment]
yeah, you nerd sniped me :P will tag and build a new release
